python interactive_gen.py --hf_path  meta-llama/Meta-Llama-3-8B   --bench_model --empty_model
python interactive_gen.py --hf_path meta-llama/Meta-Llama-3-70B  --bench_model --empty_model
python interactive_gen.py --hf_path  meta-llama/Llama-2-7b-hf  --bench_model --empty_model
python interactive_gen.py --hf_path  meta-llama/Llama-2-13b-hf   --bench_model --empty_model
python interactive_gen.py --hf_path  Qwen/Qwen3-1.7B   --bench_model --empty_model
python interactive_gen.py --hf_path  Qwen/Qwen3-4B   --bench_model --empty_model
python interactive_gen.py --hf_path  Qwen/Qwen3-8B   --bench_model --empty_model
python interactive_gen.py --hf_path  Qwen/Qwen3-14B   --bench_model --empty_model
python interactive_gen.py --hf_path  Qwen/Qwen3-32B   --bench_model --empty_model